import { ChangeEvent, DragEvent, useMemo, useRef, useState } from "react";

type Status = "good" | "warning" | "bad" | "unknown";
type EvidenceBound = { evidence_image_ids?: string[] };
type WarningItem = { code: string; image_id?: string; message: string };
type ImageAsset = { image_id: string; file_name: string; source_path?: string; image_type?: string; competitor_id?: string };
type AnalysisItem = EvidenceBound & { conclusion?: string; finding?: string; importance?: "high" | "medium" | "low" };
type PageAnalysis = { title?: string; strengths?: AnalysisItem[]; reusable_points?: AnalysisItem[]; weaknesses?: AnalysisItem[]; reference_media?: Array<EvidenceBound & { note?: string }> };
type Competitor = { competitor_id: string; competitor_name?: string; sku?: string; asin?: string; brand?: string; completeness_score?: { value: number | null; unit?: string; status?: Status }; summary_fields?: Array<{ label: string; value: string }>; hero_media?: EvidenceBound & { image_alt?: string; caption?: string }; selling_point_evidence?: { title?: string; items?: Array<EvidenceBound & { selling_point?: string; evidence_type?: string; copy_refs?: string[]; proof_strength?: string; note?: string }> } };
type UserQuestion = EvidenceBound & { question_id?: string; label?: string; question?: string; result?: string; status?: Status };
type Opportunity = EvidenceBound & { opportunity?: string; competitor_gap?: string; demand_evidence?: string; recommended_expression?: string; validation_method?: string; risk?: string; priority?: string };
type Feature = EvidenceBound & { feature?: string; current_expression?: string; evidence_strength?: string; evaluation?: string; stronger_visual_suggestion?: string; priority?: string };
type Barrier = EvidenceBound & { user_concern?: string; current_page_answer?: string; current_material_problem?: string; proposed_image_solution?: string; launch_validation?: string; priority?: string };
type DashboardData = {
  schema_version?: string; report_meta: Record<string, unknown>; header_cards?: Array<{ label?: string; value?: string; tone?: string }>;
  competitor_visual_analysis: { method_note?: string; active_competitor_id?: string; competitors?: Competitor[] };
  competitor_page_analysis: PageAnalysis; a_plus_analysis: PageAnalysis; user_view_validation: { title?: string; questions?: UserQuestion[] };
  opportunity_validation_plan: { title?: string; items?: Opportunity[] }; feature_visualization_list: { title?: string; items?: Feature[] }; purchase_barrier_solution: { title?: string; items?: Barrier[] };
  image_assets: ImageAsset[]; input_assessment?: { access?: string; reasons?: string[] }; warnings: WarningItem[]; unknown_fields: Record<string, unknown>;
};
type ResolvedImage = { image_id: string; file_name: string; url: string };

const emptyPageAnalysis = (): PageAnalysis => ({ strengths: [], reusable_points: [], weaknesses: [], reference_media: [] });
const emptyData = (): DashboardData => ({ report_meta: {}, competitor_visual_analysis: { competitors: [] }, competitor_page_analysis: emptyPageAnalysis(), a_plus_analysis: emptyPageAnalysis(), user_view_validation: { questions: [] }, opportunity_validation_plan: { items: [] }, feature_visualization_list: { items: [] }, purchase_barrier_solution: { items: [] }, image_assets: [], warnings: [], unknown_fields: {} });
const modules = ["competitor_visual_analysis", "competitor_page_analysis", "a_plus_analysis", "user_view_validation", "opportunity_validation_plan", "feature_visualization_list", "purchase_barrier_solution", "image_assets"];
const isRecord = (value: unknown): value is Record<string, unknown> => Boolean(value) && typeof value === "object" && !Array.isArray(value);
const arr = <T,>(value: unknown): T[] => Array.isArray(value) ? value as T[] : [];
const text = (value: unknown) => typeof value === "string" && value.trim() ? value : "待补充";
const optionalText = (value: unknown) => typeof value === "string" ? value : undefined;
function note(data: DashboardData, code: string, message: string, image_id?: string) { const item = { code, message, image_id }; data.warnings.push(item); console.warn(`[${code}]${image_id ? ` ${image_id}:` : ""} ${message}`); }
function normalizeStatus(value: unknown): Status | undefined { if (value === "supported") return "good"; if (value === "mixed") return "warning"; return value === "good" || value === "warning" || value === "bad" || value === "unknown" ? value : undefined; }
function normalizePageAnalysis(value: unknown): PageAnalysis { if (!isRecord(value)) return emptyPageAnalysis(); const normalizeItems = (items: unknown) => arr<AnalysisItem>(items).map((item) => ({ ...item, conclusion: item.conclusion ?? item.finding })); return { ...value, strengths: normalizeItems(value.strengths), reusable_points: normalizeItems(value.reusable_points), weaknesses: normalizeItems(value.weaknesses), reference_media: arr(value.reference_media) }; }
function normalizeCompetitor(value: unknown): Competitor { const raw = isRecord(value) ? value : {}; const facts = arr<Record<string, unknown>>(raw.page_facts); const ledger = arr<Record<string, unknown>>(raw.selling_point_ledger); const legacyItems = ledger.map((item) => ({ selling_point: optionalText(item.feature), evidence_type: optionalText(item.classification), copy_refs: arr<string>(item.copy_refs), proof_strength: optionalText(item.confidence), note: [item.advantage, item.benefit].filter((part): part is string => typeof part === "string" && Boolean(part)).join(" "), evidence_image_ids: arr<string>(item.evidence_image_ids) })); const existingSelling = isRecord(raw.selling_point_evidence) ? raw.selling_point_evidence as Competitor["selling_point_evidence"] : undefined; const id = typeof raw.competitor_id === "string" ? raw.competitor_id : ""; return { ...raw, competitor_id: id, competitor_name: typeof raw.competitor_name === "string" ? raw.competitor_name : id === "competitor_unknown" ? "竞品分析" : id || undefined, summary_fields: arr(raw.summary_fields).length ? arr<{ label: string; value: string }>(raw.summary_fields) : facts.map((fact) => ({ label: typeof fact.classification === "string" ? fact.classification : "页面事实", value: typeof fact.statement === "string" ? fact.statement : "" })), selling_point_evidence: existingSelling ?? { title: "卖点与图像证据", items: legacyItems }, }; }

function normalize(raw: unknown): DashboardData {
  if (!isRecord(raw)) throw new Error("JSON 根节点必须是对象。");
  const data = emptyData(); data.schema_version = typeof raw.schema_version === "string" ? raw.schema_version : undefined;
  data.report_meta = isRecord(raw.report_meta) ? { ...raw.report_meta, data_scope: raw.report_meta.data_scope ?? raw.report_meta.scope } : {}; data.header_cards = Array.isArray(raw.header_cards) ? arr(raw.header_cards) : isRecord(raw.header_cards) ? Object.entries(raw.header_cards).map(([label, value]) => ({ label: ({ material_availability: "素材可用性", visible_product_category: "可见品类", overall_summary: "整体摘要" } as Record<string, string>)[label] ?? label, value: typeof value === "string" ? value : "" })) : undefined;
  const rawVisual = isRecord(raw.competitor_visual_analysis) ? raw.competitor_visual_analysis : {}; data.competitor_visual_analysis = { method_note: typeof rawVisual.method_note === "string" ? rawVisual.method_note : typeof rawVisual.analysis_basis === "string" ? rawVisual.analysis_basis : undefined, active_competitor_id: typeof rawVisual.active_competitor_id === "string" ? rawVisual.active_competitor_id : undefined, competitors: arr(rawVisual.competitors).map(normalizeCompetitor) };
  data.competitor_page_analysis = normalizePageAnalysis(raw.competitor_page_analysis); data.a_plus_analysis = normalizePageAnalysis(raw.a_plus_analysis);
  const rawValidation = isRecord(raw.user_view_validation) ? raw.user_view_validation : {}; data.user_view_validation = { title: typeof rawValidation.title === "string" ? rawValidation.title : undefined, questions: arr<UserQuestion>(rawValidation.questions).map((item) => ({ ...item, question_id: item.question_id ?? (item as UserQuestion & { id?: string }).id, status: normalizeStatus(item.status) })) }; data.opportunity_validation_plan = isRecord(raw.opportunity_validation_plan) ? raw.opportunity_validation_plan as DashboardData["opportunity_validation_plan"] : { items: [] }; data.feature_visualization_list = isRecord(raw.feature_visualization_list) ? raw.feature_visualization_list as DashboardData["feature_visualization_list"] : { items: [] }; data.purchase_barrier_solution = isRecord(raw.purchase_barrier_solution) ? raw.purchase_barrier_solution as DashboardData["purchase_barrier_solution"] : { items: [] };
  data.image_assets = arr<ImageAsset>(raw.image_assets); data.input_assessment = isRecord(raw.input_assessment) ? raw.input_assessment as DashboardData["input_assessment"] : undefined; data.warnings = arr<WarningItem>(raw.warnings).slice();
  Object.entries(raw).forEach(([key, value]) => { if (!["schema_version", "report_meta", "header_cards", ...modules, "input_assessment", "warnings"].includes(key)) data.unknown_fields[key] = value; });
  if (typeof data.report_meta.report_title !== "string") note(data, "MISSING_REQUIRED_FIELD", "缺少 report_meta.report_title"); modules.forEach((key) => { if (!(key in raw)) note(data, "MISSING_REQUIRED_MODULE", `缺少固定模块 ${key}`); });
  return data;
}

function buildImageIndex(data: DashboardData, files: File[]) { const index = new Map<string, ResolvedImage>(); const names = new Map<string, File[]>(); files.forEach((file) => names.set(file.name, [...(names.get(file.name) ?? []), file])); const ids = new Set<string>(); data.image_assets.forEach((asset) => { if (ids.has(asset.image_id)) { note(data, "DUPLICATE_IMAGE_ID", "图片 ID 重复，已跳过", asset.image_id); return; } ids.add(asset.image_id); const matches = names.get(asset.file_name) ?? []; if (matches.length !== 1) { note(data, "UNRESOLVED_IMAGE", "图片文件名未找到或不唯一", asset.image_id); return; } index.set(asset.image_id, { image_id: asset.image_id, file_name: asset.file_name, url: URL.createObjectURL(matches[0]) }); }); return index; }
function images(item: EvidenceBound, index: Map<string, ResolvedImage>, data: DashboardData) { return (item.evidence_image_ids ?? []).flatMap((id) => { const image = index.get(id); if (!image) note(data, "UNKNOWN_EVIDENCE_IMAGE", "引用图片不可用", id); return image ? [image] : []; }); }

function Evidence({ value }: { value: ResolvedImage[] }) { const [selected, setSelected] = useState<ResolvedImage | null>(null); if (!value.length) return null; return <><div className="evidence-wrap"><div className="evidence-images">{value.map((image) => <img src={image.url} key={image.image_id} alt={image.file_name} onDoubleClick={() => setSelected(image)} />)}</div></div>{selected && <div className="image-lightbox" role="dialog" aria-modal="true" aria-label={selected.file_name} onClick={() => setSelected(null)}><div className="image-lightbox-content" onClick={(event) => event.stopPropagation()}><button className="image-lightbox-close" aria-label="关闭图片预览" onClick={() => setSelected(null)}>×</button><img src={selected.url} alt={selected.file_name} /><p>{selected.file_name}</p></div></div>}</>; }
function StatusBadge({ value = "unknown" }: { value?: string }) { return <span className={`status ${value}`}>{value === "good" ? "良好" : value === "warning" ? "需关注" : value === "bad" ? "风险" : "待补充"}</span>; }
function EvidenceKind({ value }: { value?: string }) { const isFact = value === "fact"; return <span className={`evidence-kind ${isFact ? "fact" : "observation"}`}><b aria-hidden="true">{isFact ? "✓" : "◌"}</b>{isFact ? "事实" : value === "observation" ? "观察" : text(value)}</span>; }
function ProofStrength({ value }: { value?: string }) { const label = value === "high" ? "高可信" : value === "medium" ? "中可信" : value === "weak" ? "低可信" : text(value); return <span className={`proof-strength ${value ?? "unknown"}`}><i aria-hidden="true" /><i aria-hidden="true" /><i aria-hidden="true" />{label}</span>; }
function AnalysisGroupTitle({ title }: { title: string }) { const meta = title === "优点" ? ["✓", "strength"] : title === "可借鉴点" ? ["↗", "reusable"] : ["!", "weakness"]; return <h3 className={`analysis-group-title ${meta[1]}`}><b aria-hidden="true">{meta[0]}</b>{title}</h3>; }
function EmptyState() { return <div className="empty-state">暂无已提供内容</div>; }
function Section({ number, title, children }: { number: string; title: string; children: React.ReactNode }) { return <section className="report-section"><header><span>{number}</span><h2>{title}</h2></header>{children}</section>; }

function Header({ data }: { data: DashboardData }) { const meta = data.report_meta; const fields = [["产品", meta.product_name], ["类目", meta.product_category], ["站点", meta.marketplace], ["分析方法", meta.analysis_method], ["生成时间", meta.generated_at], ["数据范围", meta.data_scope]].filter(([, value]) => value !== undefined); return <><section className="report-hero"><p className="eyebrow">IPD VISUAL MARKET ANALYSIS</p><h1>{text(meta.report_title)}</h1>{fields.length > 0 && <div className="meta">{fields.map(([label, value]) => <span key={String(label)}>{text(label)} · {text(value)}</span>)}</div>}{meta.analyst_note !== undefined && <p>{text(meta.analyst_note)}</p>}{data.input_assessment?.access === "failed" && <aside className="failure-note"><b>素材访问失败</b>{(data.input_assessment.reasons ?? []).map((reason) => <p key={reason}>{reason}</p>)}</aside>}</section>{data.header_cards?.length ? <div className="header-cards">{data.header_cards.map((card, i) => <article className={`header-card ${card.tone ?? "neutral"}`} key={`${card.label}-${i}`}><p>{text(card.label)}</p><strong>{text(card.value)}</strong></article>)}</div> : null}</>; }

function CompetitorVisual({ data, index }: { data: DashboardData; index: Map<string, ResolvedImage> }) { const competitors = data.competitor_visual_analysis.competitors ?? []; const requested = data.competitor_visual_analysis.active_competitor_id; const [active, setActive] = useState(requested ?? competitors[0]?.competitor_id ?? ""); const current = competitors.find((item) => item.competitor_id === active) ?? competitors[0]; if (!current) return <EmptyState />; const details = [["SKU", current.sku], ["ASIN", current.asin], ["品牌", current.brand]]; const selling = current.selling_point_evidence?.items ?? []; const facts = current.summary_fields ?? []; return <><div className="tabs">{competitors.map((item) => <button className={item.competitor_id === current.competitor_id ? "active" : ""} onClick={() => setActive(item.competitor_id)} key={item.competitor_id}>{text(item.competitor_name)}</button>)}</div><p className="method-note">{data.competitor_visual_analysis.method_note}</p><div className="competitor-title-row"><h3>{text(current.competitor_name)}</h3><div className="competitor-facts">{details.map(([label, value]) => value !== undefined && <p key={label}><span>{label}</span>{text(value)}</p>)}{current.completeness_score && <p><span>素材完整度</span><b>{current.completeness_score.value ?? "待补充"}{current.completeness_score.unit ?? ""}</b><StatusBadge value={current.completeness_score.status} /></p>}</div></div>{facts.length > 0 && <div className="visual-card-row">{facts.map((field, i) => <article className="fact-card" key={`${field.label}-${i}`}><p>{text(field.label)}</p><strong>{text(field.value)}</strong></article>)}</div>}<div className="selling-cards"><p className="eyebrow">{current.selling_point_evidence?.title ?? "卖点与图像证据"}</p>{selling.length ? <div className="selling-card-row">{selling.map((item, i) => <article className="selling-card" key={`${item.selling_point}-${i}`}><div className="selling-meta"><EvidenceKind value={item.evidence_type} /><ProofStrength value={item.proof_strength} /></div><h3>{text(item.selling_point)}</h3><p>{text(item.note)}</p>{item.copy_refs?.length ? <p className="copy-ref">{item.copy_refs.join("、")}</p> : null}<Evidence value={images(item, index, data)} /></article>)}</div> : <EmptyState />}</div></>; }

function PagePanel({ data, analysis, index }: { data: DashboardData; analysis: PageAnalysis; index: Map<string, ResolvedImage> }) { const groups: Array<[string, AnalysisItem[] | undefined]> = [["优点", analysis.strengths], ["可借鉴点", analysis.reusable_points], ["缺点", analysis.weaknesses]]; const references = analysis.reference_media ?? []; const hasContent = groups.some(([, items]) => (items ?? []).length) || references.length; if (!hasContent) return <EmptyState />; return <div className={`analysis-layout ${references.length ? "" : "no-reference"}`}><div className="analysis-groups">{groups.map(([title, items]) => <div key={title}><AnalysisGroupTitle title={title} />{items?.length ? items.map((item, i) => <article className="analysis-item" key={`${title}-${i}`}><span className={`priority ${item.importance ?? "low"}`}>{item.importance ?? "low"}</span><p>{text(item.conclusion ?? item.finding)}</p><Evidence value={images(item, index, data)} /></article>) : <p className="pending">待补充</p>}</div>)}</div>{references.length > 0 && <aside className="reference-media"><p className="eyebrow">参考图片</p>{references.map((item, i) => <div key={i}><Evidence value={images(item, index, data)} />{item.note !== undefined && <p>{text(item.note)}</p>}</div>)}</aside>}</div>; }

function UserValidation({ data, index }: { data: DashboardData; index: Map<string, ResolvedImage> }) { const labels: Array<[string, string]> = [["q_3s", "3 秒理解"], ["q_10s", "10 秒找信息"], ["q_memory", "记忆点"], ["q_purchase", "主要购买疑虑"]]; const questions = data.user_view_validation.questions ?? []; return <div className="validation-list">{labels.map(([id, fallback]) => { const item = questions.find((question) => question.question_id === id); return <article key={id}><div><p className="eyebrow">{item?.label ?? fallback}</p><h3>{item?.question ? item.question : fallback}</h3></div><div><StatusBadge value={item?.status} /><p>{item ? text(item.result) : "待补充"}</p><Evidence value={item ? images(item, index, data) : []} /></div></article>; })}</div>; }

function Table({ headers, rows }: { headers: string[]; rows: React.ReactNode[][] }) { return <div className="table-wrap"><table><thead><tr>{headers.map((header) => <th key={header}>{header}</th>)}</tr></thead><tbody>{rows.map((row, i) => <tr key={i}>{row.map((cell, j) => <td key={j}>{cell}</td>)}</tr>)}</tbody></table></div>; }
function Priority({ value }: { value?: string }) { return value ? <span className="priority p-code">{value}</span> : null; }
function DynamicTable<T extends EvidenceBound>({ data, index, items, headers, render }: { data: DashboardData; index: Map<string, ResolvedImage>; items?: T[]; headers: string[]; render: (item: T) => React.ReactNode[] }) { return items?.length ? <Table headers={headers} rows={items.map((item) => [...render(item), <Priority value={(item as T & { priority?: string }).priority} />, <Evidence value={images(item, index, data)} />])} /> : <EmptyState />; }

function Dashboard({ data, index, onReset }: { data: DashboardData; index: Map<string, ResolvedImage>; onReset: () => void }) { if (data.schema_version !== "ipd-visual-market-analysis-v1") return <main className="error-page"><p className="eyebrow">INPUT CONTRACT ERROR</p><h1>协议不兼容</h1><p>仅支持 <code>ipd-visual-market-analysis-v1</code> 格式的报告。</p><button onClick={onReset}>重新导入</button></main>; const displayData = data.input_assessment?.access === "failed" ? { ...data, competitor_visual_analysis: { competitors: [] }, competitor_page_analysis: emptyPageAnalysis(), a_plus_analysis: emptyPageAnalysis(), user_view_validation: { questions: [] }, opportunity_validation_plan: { items: [] }, feature_visualization_list: { items: [] }, purchase_barrier_solution: { items: [] } } : data; return <main className="page v2-page"><header className="topbar"><div className="brand"><span>IPD</span><p>视觉市场分析</p></div><button className="secondary-button" onClick={onReset}>更换报告</button></header><div className="container"><Header data={displayData} /><Section number="01" title="竞品视觉分析"><CompetitorVisual data={displayData} index={index} /></Section><Section number="02" title={displayData.competitor_page_analysis.title ?? "竞品分析"}><PagePanel data={displayData} analysis={displayData.competitor_page_analysis} index={index} /></Section><Section number="03" title={displayData.a_plus_analysis.title ?? "A+ 页面分析"}><PagePanel data={displayData} analysis={displayData.a_plus_analysis} index={index} /></Section><Section number="04" title={displayData.user_view_validation.title ?? "用户视角验证"}><UserValidation data={displayData} index={index} /></Section><Section number="05" title={displayData.opportunity_validation_plan.title ?? "机会点与验证计划"}><DynamicTable data={displayData} index={index} items={displayData.opportunity_validation_plan.items} headers={["机会点", "竞品缺口", "需求依据", "建议表达", "验证方式", "风险", "优先级", "证据"]} render={(item) => [text(item.opportunity), text(item.competitor_gap), text(item.demand_evidence), text(item.recommended_expression), text(item.validation_method), text(item.risk)]} /></Section><Section number="06" title={displayData.feature_visualization_list.title ?? "功能可视化列表"}><DynamicTable data={displayData} index={index} items={displayData.feature_visualization_list.items} headers={["功能", "当前表达方式", "证据强度", "评估", "更强视觉建议", "优先级", "证据"]} render={(item) => [text(item.feature), text(item.current_expression), text(item.evidence_strength), text(item.evaluation), text(item.stronger_visual_suggestion)]} /></Section><Section number="07" title={displayData.purchase_barrier_solution.title ?? "购买阻力到图像解决方案"}><DynamicTable data={displayData} index={index} items={displayData.purchase_barrier_solution.items} headers={["用户在想什么", "当前页面是否回答", "当前素材问题", "我方图像解决方案", "上线前验证", "优先级", "证据"]} render={(item) => [text(item.user_concern), text(item.current_page_answer), text(item.current_material_problem), text(item.proposed_image_solution), text(item.launch_validation)]} /></Section></div></main>; }

export default function App() { const [data, setData] = useState<DashboardData | null>(null); const [pending, setPending] = useState<DashboardData | null>(null); const [files, setFiles] = useState<File[]>([]); const [error, setError] = useState<string | null>(null); const [dragging, setDragging] = useState(false); const jsonInput = useRef<HTMLInputElement>(null); const folderInput = useRef<HTMLInputElement>(null); const index = useMemo(() => data ? buildImageIndex(data, files) : new Map<string, ResolvedImage>(), [data, files]); const load = async (file?: File) => { if (!file) return; try { setPending(normalize(JSON.parse(await file.text()))); setError(null); } catch (reason) { setPending(null); setError(reason instanceof Error ? reason.message : "无法解析 JSON 文件。"); } }; const reset = () => { index.forEach((image) => URL.revokeObjectURL(image.url)); setData(null); setPending(null); setFiles([]); setError(null); }; if (data) return <Dashboard data={data} index={index} onReset={reset} />; return <main className="upload-page"><header className="brand"><span>IPD</span><p>视觉市场分析</p></header><section className="upload-intro"><p className="eyebrow">IPD VISUAL MARKET ANALYSIS</p><h1>导入竞品分析报告</h1><p>上传 V2.0 JSON 报告与原始图片目录，确认文件后进入固定市场分析看板。</p></section><section className={`dropzone ${dragging ? "is-dragging" : ""}`} onDragOver={(event) => { event.preventDefault(); setDragging(true); }} onDragLeave={() => setDragging(false)} onDrop={(event: DragEvent<HTMLDivElement>) => { event.preventDefault(); setDragging(false); void load(event.dataTransfer.files[0]); }}><div className="upload-icon">↑</div><h2>拖入 JSON 报告</h2><p>{pending ? "报告已解析，继续选择图片目录。" : "支持 ipd-visual-market-analysis-v1"}</p><button onClick={() => jsonInput.current?.click()}>{pending ? "更换 JSON 报告" : "选择 JSON 报告"}</button><input ref={jsonInput} type="file" accept="application/json,.json" onChange={(event: ChangeEvent<HTMLInputElement>) => void load(event.target.files?.[0])} /></section><section className="image-picker"><div><p className="eyebrow">必填</p><h2>选择原始图片目录</h2><p>{files.length ? `已载入 ${files.length} 个文件，仅按唯一文件名关联证据图。` : "仅按唯一文件名关联证据图，不读取报告中的路径。"}</p></div><button className="secondary-button" onClick={() => folderInput.current?.click()}>{files.length ? "更换图片目录" : "选择图片目录"}</button><input ref={folderInput} type="file" multiple {...({ webkitdirectory: "", directory: "" } as Record<string, string>)} onChange={(event: ChangeEvent<HTMLInputElement>) => setFiles(Array.from(event.target.files ?? []))} /></section><button className="enter-dashboard" disabled={!pending || !files.length} onClick={() => pending && setData(pending)}>进入市场分析看板</button>{(!pending || !files.length) && <p className="entry-hint">请先选择 JSON 报告和图片目录。</p>}{error && <p className="upload-error">{error}</p>}</main>; }
